pipeline {
    agent any

    environment {
        VIRTUALENV_HOME = "${WORKSPACE}/venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/donald-alphonso/alx-backend-python.git'
                dir('messaging_app') {
                    echo "Code checked out"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m venv venv'
                    sh './venv/bin/pip3 install --upgrade pip'
                    sh './venv/bin/pip3 install -r ../requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh './venv/bin/pytest --junitxml=report.xml || echo "Tests completed"'
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit allowEmptyResults: true, testResults: 'messaging_app/report.xml'
            }
        }
    }

    triggers {
        // Aucun déclencheur automatique : pipeline manuel
    }
}